name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace Firebase Config Placeholders
        run: |
          sed -i "s/\${FIREBASE_API_KEY}/${{ secrets.FIREBASE_API_KEY }}/g" index.js
          sed -i "s/\${FIREBASE_AUTH_DOMAIN}/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" index.js
          sed -i "s/\${FIREBASE_PROJECT_ID}/${{ secrets.FIREBASE_PROJECT_ID }}/g" index.js
          sed -i "s/\${FIREBASE_STORAGE_BUCKET}/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" index.js
          sed -i "s/\${FIREBASE_MESSAGING_SENDER_ID}/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" index.js
          sed -i "s/\${FIREBASE_APP_ID}/${{ secrets.FIREBASE_APP_ID }}/g" index.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Assumes your site files (index.html, index.js, etc.) are in the root